production:
  adapter: postgresql
  encoding: unicode
  database: bookstore_production
  host: localhost
  pool: 5
  username: postgres
  password: postgres

development:
  adapter: postgresql
  encoding: unicode
  database: bookstore_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: bookstore_test
  pool: 5
  username: postgres
  password: postgres
