# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ecbfe8s14d075b939ce76fb3af7e2b1f064ea71710892e8d614d59ad8093e18178f231b71e3184d496673cc494533c92d7570fecab25617d3c0d5a2085e03f5
  GITHUB_KEY: fae28765b85d0f1e69ca
  GITHUB_SECRET: 55bda2d413833e43d0cc8401a61a3d7dbded6110

test:
  secret_key_base: 45913ba038bc024b363664ad869b6dd70455dbea0b5b820e730364f934acfac83b6c08e555d5a463c753ee9a820b3f2b810e191eca725b653b253085a25f08fd
  
production:
  secret_key_base: secret
  secret_token: secret
  GITHUB_KEY: fae28765b85d0f1e69ca
  GITHUB_SECRET: 55bda2d413833e43d0cc8401a61a3d7dbded6110
