source 'https://rubygems.org'


gem 'rails', '4.2.5.2'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc


gem 'pry'
gem 'shopping_cart', path: '../../'

gem 'normalize-rails'
source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap'
end

gem 'rails_admin'

gem 'carrierwave'
gem "mini_magick"

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
